#!/bin/sh
export LC_ALL="en_US.UTF-8"
if [ -z "$DEVENV_SHELL_CMD" ]; then
    touch ~/.xonshrc
    export SHELL=bash
    exec xonsh --rc $DEVENV_ROOT/.xonshrc
else
    cd "$DEVENV_SHELL_CD"
    export SHELL=bash
    exec sh -c "$DEVENV_SHELL_CMD"
fi

